ApiClient/Models/ErrorViewModel.cs
namespace ApiClient.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ApiClient/Models/RobotModel.cs
namespace ApiClient.Models
{
    public class RobotModel
    {
        public required string Name { get; set; }
        public required double[][] Configuration { get; set; }

        public required int[][] AngleFreedom { get; set; }
    }
}

ApiClient/Controllers/ApiController.cs
using ApiClient.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Threading.Tasks;

public class ApiController : Controller
{
    private readonly ServiceStatusProvider _serviceStatusProvider;
    private readonly HttpClient _httpClient;
    private readonly ILogger<HomeController> _logger;

    public ApiController(ServiceStatusProvider serviceStatusProvider,  HttpClient httpClient, ILogger<HomeController> logger)
    {
        _serviceStatusProvider = serviceStatusProvider;
        _httpClient = httpClient;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        var serviceStatus = new Dictionary<string, string>();

        ViewData["ServiceStatus"] = await _serviceStatusProvider.GetServiceStatus(_httpClient);
        return View();
    }

    #region old upload methode using post on the same page
    //[HttpPost]
    //public async Task<IActionResult> Upload(IFormFile file)
    //{
    //    if (file == null || file.Length == 0)
    //    {
    //        return BadRequest("No file uploaded.");
    //    }

    //    if(_serviceStatusProvider.currentStatus == null)
    //    {
    //        await _serviceStatusProvider.GetServiceStatus(_httpClient);
    //    }

    //    using var content = new MultipartFormDataContent();
    //    using var fileStream = file.OpenReadStream();
    //    var fileContent = new StreamContent(fileStream);
    //    fileContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(file.ContentType);
    //    content.Add(fileContent, "image", file.FileName);

    //    var response = await _httpClient.PostAsync("http://localhost:5000/yoloDetection/detect", content);
    //    if (response.IsSuccessStatusCode)
    //    {
    //        var result = await response.Content.ReadAsStringAsync();

    //        ViewData["ServiceStatus"] = _serviceStatusProvider.currentStatus!;

    //        return View("Index");
    //    }

    //    return BadRequest("Failed to upload file.");
    //}

    #endregion
}

ApiClient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ApiClient.Models;

namespace ApiClient.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ApiClient/Controllers/RobotController.cs
using ApiClient.Controllers;
using ApiClient.Models;
using ApiClient.Services;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Threading.Tasks;

namespace ApiClient.RobotController;

public class RobotController : Controller
{
    private readonly ServiceRobot _serviceRobot;
    private readonly HttpClient _httpClient;
    
    public RobotController(ServiceRobot serviceRobot, HttpClient httpClient)
    {
        _serviceRobot = serviceRobot;
        _httpClient = httpClient;
    }

    public async Task<IActionResult> Index()
    {
        List<RobotModel>? robotsAvailable = await _serviceRobot.GetRobots(_httpClient);


        ViewData["robotsAvailable"] = (robotsAvailable != null)? robotsAvailable! : [];

        return View();
    }

}

ApiClient/Views/Home/Index.cshtml
@{
    //ViewData["Title"] = "API Microservice Status";
    //var serviceStatus = ViewData["ServiceStatus"] as Dictionary<string, string>;
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<h1>Microservice Status</h1>

<table>
    <thead>
        <tr>
            <th>Service</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Users Service</td>
        </tr>
        <tr>
            <td>Orders Service</td>
        </tr>
        <tr>
            <td>Products Service</td> 
        </tr>
    </tbody>
</table>

<style>
    table {
        width: 50%;
        border-collapse: collapse;
        margin: 20px 0;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
    }
    th {
        background-color: #f4f4f4;
    }
    td {
        text-align: center;
    }
    .online {
        color: green;
    }
    .offline {
        color: red;
    }
</style>

ApiClient/Views/Robot/index.cshtml
@{
    ViewData["Title"] = "Robot";
    List<RobotModel> robotsAvailable = ViewData["robotsAvailable"] as List<RobotModel>;
}

<h1>Robot Pick and Drop</h1>
<br />
<br />
<div id="container">
    <div id="left">
        <h2>Configuration of robot and detection model</h2>
        <label for="robot-select">Choose a robot:</label>
        <br />
        <select name="robot" id="robot-select" onchange="initRobot(this.value)">
            @if (robotsAvailable != null && robotsAvailable.Count > 0)
            {
                foreach (var robot in robotsAvailable)
                {
                    string jsonConfig = Newtonsoft.Json.JsonConvert.SerializeObject(robot.Configuration);
                    string jsonAngleFreedom = Newtonsoft.Json.JsonConvert.SerializeObject(robot.AngleFreedom);
                    <option value="@robot.Name" data-configuration="@Html.Raw(jsonConfig)" data-anglefreedom="@Html.Raw(jsonAngleFreedom)">@robot.Name</option>
                }
            }
            else
            {
                <option value="">No robots available</option>
            }
        </select>
        <br />
        <label for="model-select">Choose a model:</label>
        <br />
        <select name="model" id="model-select" onchange="initModel(this.value)">
            <option value="yolov8n">YOLOV8 cocodataset</option>
            <option value="nutYolov8m">YOLOV8 custom nut dataset</option>
        </select>
        <br /> <br />
        <h2>Targets configuration </h2>
        <form onsubmit="generateTargetBaseOnImage(event)">
            <table>
               
                <tbody>
                    <tr>
                        <td><input type="file" id="image" name="file" accept=".jpg, .jpeg" required /></td>
                    </tr>
                    <tr>
                        <td><img src="" id="preview" /></td>
                        <td><canvas id="canvasYoloTest"></canvas></td>
                    </tr>
                    <tr>
                        <td><button type="submit">Detection and set target</button></td>
                    </tr>
                </tbody>
            </table>

        </form>

        <script src="~/js/model.js"></script>
        <br />
        <button onclick="launchPickAndDrop()">Pick and Drop</button>

    </div>
    <div id="right"></div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>

<script src="~/js/robotGUI.js"></script>

<style>
    #container {
        display: flex;
        width: 100%;
        height: 100%;
    }

    #left {
        width: 50%;
        display: block;
    }

    #right {
        padding: 20px;
        width: 40%;
    }

    canvas {
        display: block;
    }

</style>

ApiClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApiClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Api" asp-action="Index">Dashboard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Api" asp-action="Index">Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Robot" asp-action="Index">Robot</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ApiClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>